name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - run: docker build -t siddharthss123ss/3tier-backend ./backend
      - run: docker push siddharthss123ss/3tier-backend

      - run: docker build -t siddharthss123ss/3tier-frontend ./frontend
      - run: docker push siddharthss123ss/3tier-frontend